"""Добавил таблицу для резервации

Revision ID: 1a7d02517592
Revises: 3b73adf707a5
Create Date: 2024-07-22 04:07:37.146181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7d02517592'
down_revision: Union[str, None] = '3b73adf707a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reservation',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_reservation_book_id_book'), onupdate='RESTRICT', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_reservation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_reservation')
    # ### end Alembic commands ###
