"""Тест миграция

Revision ID: 3aaed3e8ca58
Revises: 1a7d02517592
Create Date: 2024-07-22 11:21:48.921464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaed3e8ca58'
down_revision: Union[str, None] = '1a7d02517592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_book_reservation_book_id_book'), 'book_reservation', 'book', ['book_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT', use_alter=True)
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genre', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_book_reservation_book_id_book'), 'book_reservation', type_='foreignkey')
    # ### end Alembic commands ###
