"""Добавил is_deleted

Revision ID: 9a205730f5fa
Revises: 4540cfa12d90
Create Date: 2024-07-21 22:20:41.185603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a205730f5fa'
down_revision: Union[str, None] = '4540cfa12d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_book_author_id_user'), 'book', 'user', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_book_genre_book_id_book'), 'book_genre', 'book', ['book_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key(op.f('fk_book_genre_genre_id_genre'), 'book_genre', 'genre', ['genre_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_genre_genre_id_genre'), 'book_genre', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_book_id_book'), 'book_genre', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_author_id_user'), 'book', type_='foreignkey')
    # ### end Alembic commands ###
